import { getMarketplace, type MarketplaceId } from "@/lib/marketplaces";

export type ListingExportPayload = {
  title: string;
  bullets: string[];
  description?: string | null;
  backendKeywords?: string | null;
};

function escapeCsv(value: string) {
  if (/[",\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function formatListingPlain(copy: ListingExportPayload, marketplaceId: string) {
  const mp = getMarketplace(marketplaceId);
  const bullets = copy.bullets.filter(Boolean);
  const header = `# ${mp.flag} ${mp.label} listing export`;

  if (marketplaceId === "SHOPIFY") {
    return [
      header,
      "",
      "PRODUCT TITLE",
      copy.title,
      "",
      "DESCRIPTION",
      copy.description ?? "",
      "",
      "HIGHLIGHTS",
      ...bullets.map((b, i) => `${i + 1}. ${b}`),
      "",
      copy.backendKeywords ? `TAGS: ${copy.backendKeywords}` : "",
    ]
      .filter(Boolean)
      .join("\n");
  }

  if (marketplaceId === "BOL_NL") {
    return [
      header,
      mp.copyNote,
      "",
      "Titel",
      copy.title,
      "",
      "Bulletpoints",
      ...bullets.map((b, i) => `${i + 1}. ${b}`),
      "",
      "Beschrijving",
      copy.description ?? "",
      "",
      copy.backendKeywords ? `Zoektermen: ${copy.backendKeywords}` : "",
    ]
      .filter(Boolean)
      .join("\n");
  }

  return [
    header,
    mp.copyNote,
    "",
    "Title",
    copy.title,
    "",
    "Bullets",
    ...bullets.map((b, i) => `${i + 1}. ${b}`),
    "",
    "Description",
    copy.description ?? "",
    "",
    copy.backendKeywords ? `Backend keywords: ${copy.backendKeywords}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export function formatListingCsv(copy: ListingExportPayload, marketplaceId: MarketplaceId) {
  const bullets = [...copy.bullets];
  while (bullets.length < 5) bullets.push("");

  const row = [
    copy.title,
    bullets[0] ?? "",
    bullets[1] ?? "",
    bullets[2] ?? "",
    bullets[3] ?? "",
    bullets[4] ?? "",
    copy.description ?? "",
    copy.backendKeywords ?? "",
    marketplaceId,
  ].map(escapeCsv);

  const headers = [
    "title",
    "bullet_1",
    "bullet_2",
    "bullet_3",
    "bullet_4",
    "bullet_5",
    "description",
    "backend_keywords",
    "marketplace",
  ];

  return `${headers.join(",")}\n${row.join(",")}`;
}

export function listingExportFilename(slug: string, marketplaceId: string, ext: "txt" | "csv" | "json") {
  const mp = getMarketplace(marketplaceId);
  const market = mp.label.replace(/\s+/g, "-").toLowerCase();
  return `${slug}-${market}-listing.${ext}`;
}

export function exportPackReadme(marketplaceId: MarketplaceId, productName: string) {
  const mp = getMarketplace(marketplaceId);
  const lines = [
    `ProductPixl export pack — ${productName}`,
    `Marketplace: ${mp.label}`,
    "",
    "Contents:",
    "  listing/listing.txt  — paste-friendly listing copy",
    "  listing/listing.csv  — spreadsheet / bulk import",
    "  listing/listing.json — structured copy for tools",
    "  images/              — gallery modules (hero, lifestyle, detail…)",
    "",
  ];

  if (marketplaceId === "BOL_NL") {
    lines.push(
      "Bol.com upload tips:",
      "  • Use listing.txt for title, bullets, and description in Seller Centre",
      "  • Upload images from images/ in Bol’s image order (main → supporting)",
      "  • Check Zoektermen (search terms) in listing.txt before publishing",
      mp.copyNote,
      ""
    );
  } else if (marketplaceId === "SHOPIFY") {
    lines.push(
      "Shopify upload tips:",
      "  • Import listing.csv or copy from listing.txt into product admin",
      "  • Upload images/ to the product media gallery",
      "  • Map TAGS from listing.txt to Shopify product tags if shown",
      ""
    );
  } else {
    lines.push(
      "Upload tips:",
      "  • Copy from listing.txt or use listing.csv where your channel supports it",
      "  • Upload images/ in your marketplace’s recommended module order",
      mp.copyNote,
      ""
    );
  }

  lines.push("Generated by ProductPixl — https://productpixl.vercel.app");
  return lines.join("\n");
}
